### ISSUE TITLE
第一阶段任务划分

### ISSUE THREAD

**Issue by fenggang29** [pezydata/AI-Platform#13]
第一阶段

    1.用户管理

    开发人员：宋远迪 王培文

    2.导入数据

    开发人员：徐敬丽

    3.数据预览

    开发人员：韩伟   

    4.数据探索

    开发人员：韩伟 王培文 
  
    5.数据预处理
   
    开发人员：冯刚 徐敬丽 宋远迪

**Comment by mengxin212** [comment]
Finished！
