### ISSUE TITLE
Spark读写数据

### ISSUE THREAD

**Issue by mengxin212** [pezydata/AI-Platform#2]
1.关系型数据库(MySQL)、文件(行、列式)、HDFS、Hive、HBase、ES等
2.读写数据
3.DEMO程序

**Comment by wangpeiwen** [comment]
孟老师，您看看还有什么需要添加或修改的内容没有
[spark文件的读取.docx](https://github.com/pezydata/AI-Platform/files/1801743/spark.docx)

**Comment by mengxin212** [comment]
Finished!
